<?php

//index
return [
    'Aukeratu' => 'Aukeratu',
    'Prezioa: Txikienetik handienera' => 'Prezioa: Txikienetik handienera',
    'Prezioa: Handienetik txikienera' => 'Prezioa: Handienetik txikienera',
    'Bilatu izenaren arabera' => 'Bilatu izenaren arabera',
    'Produktuaren izena' => 'Produktuaren izena',
    'Filtratu prezioaren arabera' => 'Filtratu prezioaren arabera',
    'Bilatu' => 'Bilatu',
    'Ez dago produkturik zure irizpideekin.' => 'Ez dago produkturik zure irizpideekin.',
    'Gehitu Saskira' => 'Gehitu Saskira',
    'Prezioa' => 'Prezioa',
    'Menu' => 'Menu',
    'Contact' => 'Kontaktua',
    'ABE TECHNOLOGY' => 'ABE TECHNOLOGY',
    'Eskubide gustiak erreserbatuta' => 'Eskubide gustiak erreserbatuta',
    'Ongi etorri, {usuario}!' => 'Ongi etorri, {usuario}!',
    'Saioa Itxi' => 'Saioa Itxi',

    //erregistroa
    'Erregistroa' => 'Erregistroa',
    'Erregistratu' => 'Erregistratu',
    'Izena' => 'Izena',
    'Abizena' => 'Abizena',
    'Jaiotze Eguna' => 'Jaiotze Eguna',
    'Helbidea' => 'Helbidea',
    'Erabiltzaile izena' => 'Erabiltzaile izena',
    'Pasahitza' => 'Pasahitza',
    'Berriro sartu pasahitza' => 'Berriro sartu pasahitza',
    'Datu guztiak beharrezkoak dira.' => 'Datu guztiak beharrezkoak dira.',
    'Pasahitzak ez dira bat etorri.' => 'Pasahitzak ez dira bat etorri.',
    'Izen hau erabiltzen hari da.' => 'Izen hau erabiltzen hari da.',
    'Kontua ahal daukezu?' => 'Kontua ahal daukezu?',
    'Hemen login egin' => 'Hemen login egin',
    'Itzuli hasierako orrira' => 'Itzuli hasierako orrira',

    // Saioa Hasi (Login)
    'ABE TECHNOLOGY' => 'ABE TECHNOLOGY',
    'Menu' => 'Menua',
    'Kontaktua' => 'Kontaktua',
    'Login' => 'Saioa hasi',
    'Carrito' => 'Saskia',
    'Denda Informatikoa' => 'Denda Informatikoa',
    'Filtratu' => 'Filtratu',
    'Username' => 'Erabiltzaile izena',
    'Password' => 'Pasahitza',
    'Please enter your password again' => 'Berriro sartu pasahitza',
    'All fields are required.' => 'Datu guztiak beharrezkoak dira.',
    'Passwords do not match.' => 'Pasahitzak ez dira bat etorri.',
    'Username is already taken.' => 'Izen hau erabiltzen hari da.',
    'Already have an account?' => 'Kontua ahal daukezu?',
    'Login here' => 'Hemen login egin',
    'Back to homepage' => 'Itzuli hasierako orrira',

    //Produktuak
    'Prezioa' => 'Prezioa',
    'Gehitu Saskira' => 'Gehitu Saskira',
    'Ez dago produkturik.' => 'Ez dago produkturik.',
    'Produktua saskira gehitu da!' => 'Produktua saskira gehitu da!',
    'Saskia' => 'Saskia',
    'Gehitu' => 'Gehitu',
    'Produktua' => 'Produktua',
    'Desconocido' => 'Desconocido',
    'Error al agregar el producto' => 'Errore bat gertatu da produktua gehitzeko.',
    'Producto agregado al carrito' => 'Produktua saskira gehitu da.',

    //saskia
    'Zure Saskia' => 'Zure Saskia',
    'Hasiera' => 'Hasiera',
    'Saskian dauden produktuak' => 'Saskian dauden produktuak',
    'Zure saskia hutsik dago.' => 'Zure saskia hutsik dago.',
    'Argazkia' => 'Argazkia',
    'Izena' => 'Izena',
    'Kopurua' => 'Kopurua',
    'Prezioa' => 'Prezioa',
    'Argazkia ez dago' => 'Argazkia ez dago',
    'Guztira' => 'Guztira',
    'Saskia Garbitu' => 'Saskia Garbitu',
    'Erosi' => 'Erosi',
    'Erosketa arrakastatsua izan da!' => 'Erosketa arrakastatsua izan da!',

    //kontaktua
    'Hornitzaileak Kudeatu' => 'Hornitzaileak Kudeatu',
    'Hornitzaileak' => 'Hornitzaileak',
    'Hasiera' => 'Hasiera',
    'Produktuak' => 'Produktuak',
    'Log Out' => 'Log Out',
    'Hornitzailea Gehitu' => 'Hornitzailea Gehitu',
    'Enpresa Izena' => 'Enpresa Izena',
    'Produktua' => 'Produktua',
    'Produktuaren Deskripzioa' => 'Produktuaren Deskripzioa',
    'Dohaintzaren Eguna' => 'Dohaintzaren Eguna',
    'Datu guztiak beharrezkoak dira.' => 'Datu guztiak beharrezkoak dira.',
    'Gehitu' => 'Gehitu',
    'Errore bat gertatu da produktua gehitzeko.' => 'Errore bat gertatu da produktua gehitzeko.',
    'Produktua saskira gehitu da!' => 'Produktua saskira gehitu da!'
];
